// Code generated for AxMdv go-rocket-factory service
// © AxMdv 2025.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/AxMdv/go-rocket-factory/payment/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// PaymentService is an autogenerated mock type for the PaymentService type
type PaymentService struct {
	mock.Mock
}

type PaymentService_Expecter struct {
	mock *mock.Mock
}

func (_m *PaymentService) EXPECT() *PaymentService_Expecter {
	return &PaymentService_Expecter{mock: &_m.Mock}
}

// PayUserOrder provides a mock function with given fields: ctx, userUUID, orderUUID, paymentMethod
func (_m *PaymentService) PayUserOrder(ctx context.Context, userUUID string, orderUUID string, paymentMethod model.PaymentMethod) (string, error) {
	ret := _m.Called(ctx, userUUID, orderUUID, paymentMethod)

	if len(ret) == 0 {
		panic("no return value specified for PayUserOrder")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, model.PaymentMethod) (string, error)); ok {
		return rf(ctx, userUUID, orderUUID, paymentMethod)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, model.PaymentMethod) string); ok {
		r0 = rf(ctx, userUUID, orderUUID, paymentMethod)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, model.PaymentMethod) error); ok {
		r1 = rf(ctx, userUUID, orderUUID, paymentMethod)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PaymentService_PayUserOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayUserOrder'
type PaymentService_PayUserOrder_Call struct {
	*mock.Call
}

// PayUserOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - userUUID string
//   - orderUUID string
//   - paymentMethod model.PaymentMethod
func (_e *PaymentService_Expecter) PayUserOrder(ctx interface{}, userUUID interface{}, orderUUID interface{}, paymentMethod interface{}) *PaymentService_PayUserOrder_Call {
	return &PaymentService_PayUserOrder_Call{Call: _e.mock.On("PayUserOrder", ctx, userUUID, orderUUID, paymentMethod)}
}

func (_c *PaymentService_PayUserOrder_Call) Run(run func(ctx context.Context, userUUID string, orderUUID string, paymentMethod model.PaymentMethod)) *PaymentService_PayUserOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(model.PaymentMethod))
	})
	return _c
}

func (_c *PaymentService_PayUserOrder_Call) Return(transactionUUID string, err error) *PaymentService_PayUserOrder_Call {
	_c.Call.Return(transactionUUID, err)
	return _c
}

func (_c *PaymentService_PayUserOrder_Call) RunAndReturn(run func(context.Context, string, string, model.PaymentMethod) (string, error)) *PaymentService_PayUserOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewPaymentService creates a new instance of PaymentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentService {
	mock := &PaymentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
