// Code generated for AxMdv go-rocket-factory service
// © AxMdv 2025.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/AxMdv/go-rocket-factory/order/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// OrderRepository is an autogenerated mock type for the OrderRepository type
type OrderRepository struct {
	mock.Mock
}

type OrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderRepository) EXPECT() *OrderRepository_Expecter {
	return &OrderRepository_Expecter{mock: &_m.Mock}
}

// Cancel provides a mock function with given fields: ctx, orderUUID
func (_m *OrderRepository) Cancel(ctx context.Context, orderUUID string) error {
	ret := _m.Called(ctx, orderUUID)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, orderUUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrderRepository_Cancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cancel'
type OrderRepository_Cancel_Call struct {
	*mock.Call
}

// Cancel is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID string
func (_e *OrderRepository_Expecter) Cancel(ctx interface{}, orderUUID interface{}) *OrderRepository_Cancel_Call {
	return &OrderRepository_Cancel_Call{Call: _e.mock.On("Cancel", ctx, orderUUID)}
}

func (_c *OrderRepository_Cancel_Call) Run(run func(ctx context.Context, orderUUID string)) *OrderRepository_Cancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *OrderRepository_Cancel_Call) Return(_a0 error) *OrderRepository_Cancel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderRepository_Cancel_Call) RunAndReturn(run func(context.Context, string) error) *OrderRepository_Cancel_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrder provides a mock function with given fields: ctx, order
func (_m *OrderRepository) CreateOrder(ctx context.Context, order model.Order) error {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Order) error); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrderRepository_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type OrderRepository_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order model.Order
func (_e *OrderRepository_Expecter) CreateOrder(ctx interface{}, order interface{}) *OrderRepository_CreateOrder_Call {
	return &OrderRepository_CreateOrder_Call{Call: _e.mock.On("CreateOrder", ctx, order)}
}

func (_c *OrderRepository_CreateOrder_Call) Run(run func(ctx context.Context, order model.Order)) *OrderRepository_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Order))
	})
	return _c
}

func (_c *OrderRepository_CreateOrder_Call) Return(_a0 error) *OrderRepository_CreateOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderRepository_CreateOrder_Call) RunAndReturn(run func(context.Context, model.Order) error) *OrderRepository_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, orderUUID
func (_m *OrderRepository) Get(ctx context.Context, orderUUID string) (*model.Order, error) {
	ret := _m.Called(ctx, orderUUID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Order, error)); ok {
		return rf(ctx, orderUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Order); ok {
		r0 = rf(ctx, orderUUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orderUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type OrderRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID string
func (_e *OrderRepository_Expecter) Get(ctx interface{}, orderUUID interface{}) *OrderRepository_Get_Call {
	return &OrderRepository_Get_Call{Call: _e.mock.On("Get", ctx, orderUUID)}
}

func (_c *OrderRepository_Get_Call) Run(run func(ctx context.Context, orderUUID string)) *OrderRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *OrderRepository_Get_Call) Return(_a0 *model.Order, _a1 error) *OrderRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderRepository_Get_Call) RunAndReturn(run func(context.Context, string) (*model.Order, error)) *OrderRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// MarkPaid provides a mock function with given fields: ctx, orderUUID, transactionUUID, method
func (_m *OrderRepository) MarkPaid(ctx context.Context, orderUUID string, transactionUUID string, method model.PaymentMethod) error {
	ret := _m.Called(ctx, orderUUID, transactionUUID, method)

	if len(ret) == 0 {
		panic("no return value specified for MarkPaid")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, model.PaymentMethod) error); ok {
		r0 = rf(ctx, orderUUID, transactionUUID, method)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrderRepository_MarkPaid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkPaid'
type OrderRepository_MarkPaid_Call struct {
	*mock.Call
}

// MarkPaid is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID string
//   - transactionUUID string
//   - method model.PaymentMethod
func (_e *OrderRepository_Expecter) MarkPaid(ctx interface{}, orderUUID interface{}, transactionUUID interface{}, method interface{}) *OrderRepository_MarkPaid_Call {
	return &OrderRepository_MarkPaid_Call{Call: _e.mock.On("MarkPaid", ctx, orderUUID, transactionUUID, method)}
}

func (_c *OrderRepository_MarkPaid_Call) Run(run func(ctx context.Context, orderUUID string, transactionUUID string, method model.PaymentMethod)) *OrderRepository_MarkPaid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(model.PaymentMethod))
	})
	return _c
}

func (_c *OrderRepository_MarkPaid_Call) Return(_a0 error) *OrderRepository_MarkPaid_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderRepository_MarkPaid_Call) RunAndReturn(run func(context.Context, string, string, model.PaymentMethod) error) *OrderRepository_MarkPaid_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderRepository creates a new instance of OrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderRepository {
	mock := &OrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
